// Candidatos comunes para premios individuales del Mundial 2026.
// Datalist (autocomplete) — el usuario también puede escribir cualquier otro nombre.

export const COMMON_TOP_SCORERS = [
  "Kylian Mbappé",
  "Lionel Messi",
  "Erling Haaland",
  "Vinicius Junior",
  "Lamine Yamal",
  "Harry Kane",
  "Cristiano Ronaldo",
  "Mohamed Salah",
  "Lautaro Martínez",
  "Julián Álvarez",
  "Bukayo Saka",
  "Phil Foden",
  "Jude Bellingham",
  "Florian Wirtz",
  "Jamal Musiala",
  "Khvicha Kvaratskhelia",
  "Rafael Leão",
  "Bruno Fernandes",
  "Antoine Griezmann",
  "Ousmane Dembélé",
  "Kai Havertz",
  "Niclas Füllkrug",
  "Romelu Lukaku",
  "Memphis Depay",
  "Cody Gakpo",
  "Christian Pulisic",
  "Folarin Balogun",
  "Hirving Lozano",
  "Raúl Jiménez",
  "Jonathan David",
  "Alphonso Davies",
  "Kaoru Mitoma",
  "Takefusa Kubo",
  "Son Heung-min",
  "Mehdi Taremi",
  "Riyad Mahrez",
  "Hakim Ziyech",
  "Achraf Hakimi",
  "Sadio Mané",
  "Victor Osimhen",
  "Endrick",
  "Rodrygo",
  "Federico Valverde",
  "Darwin Núñez",
  "Luis Díaz",
  "James Rodríguez",
  "Enner Valencia",
];

export const COMMON_GOLDEN_GLOVES = [
  "Emiliano Martínez",
  "Thibaut Courtois",
  "Diogo Costa",
  "Mike Maignan",
  "Jordan Pickford",
  "Yassine Bounou",
  "Marc-André ter Stegen",
  "David Raya",
  "Unai Simón",
  "Manuel Neuer",
  "Wojciech Szczęsny",
  "Alisson Becker",
  "Ederson",
  "Guillermo Ochoa",
  "Matt Turner",
  "Sergio Rochet",
  "Kasper Schmeichel",
  "Yann Sommer",
];

export const COMMON_YOUNG_PLAYERS = [
  "Lamine Yamal",
  "Endrick",
  "Florian Wirtz",
  "Jamal Musiala",
  "Arda Güler",
  "Pedri",
  "Gavi",
  "Aleksandar Pavlović",
  "Warren Zaïre-Emery",
  "Désiré Doué",
  "Estêvão Willian",
  "Vitor Roque",
  "Kenan Yıldız",
  "Yıldız Kenan",
  "Antonio Nusa",
  "Kobbie Mainoo",
];
